---
R1:
    hostname: "192.168.42.101"
    groups:
        - cisco_group

R2:
    hostname: "192.168.42.102"
    groups:
        - cisco_group

R3:
    hostname: "192.168.42.103"
    groups:
        - cisco_group